# Generated by Django 3.2.3 on 2021-08-06 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210801_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.PositiveIntegerField(default=None, null=True, verbose_name='возраст'),
        ),
    ]
